// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package model

import (
	"database/sql"
	"time"
)

type Activity struct {
	ID           int64
	UserID       int64
	PatientID    sql.NullInt64
	VisitID      sql.NullInt64
	ReceptionID  sql.NullInt64
	AttachmentID sql.NullInt64
	CreatedAt    time.Time
	UpdatedAt    sql.NullTime
	DeletedAt    sql.NullTime
}

type Attachment struct {
	ID        int64
	FilePath  sql.NullString
	FileType  sql.NullString
	VisitID   sql.NullInt64
	PatientID sql.NullInt64
	CreatedAt time.Time
	UpdatedAt sql.NullTime
	DeletedAt sql.NullTime
}

type Patient struct {
	ID           int64
	FirstName    sql.NullString
	LastName     sql.NullString
	FatherName   sql.NullString
	Phone        sql.NullString
	NationalCode sql.NullString
	IdentityCode sql.NullString
	CreatedAt    time.Time
	UpdatedAt    sql.NullTime
	DeletedAt    sql.NullTime
}

type Reception struct {
	ID            int64
	ReceptionDate time.Time
	ReceptionTime time.Time
	VisitDuration int32
	InsuranceCode sql.NullString
	Description   sql.NullString
	CreatedAt     time.Time
	UpdatedAt     sql.NullTime
	DeletedAt     sql.NullTime
	PatientID     int64
}

type User struct {
	ID          int64
	UserName    string
	Password    sql.NullString
	FirstName   sql.NullString
	LastName    sql.NullString
	Description sql.NullString
}

type Visit struct {
	ID          int64
	VisitPrice  sql.NullInt64
	VisitDate   sql.NullTime
	VisitTime   sql.NullTime
	PaymentType sql.NullString
	IsPaid      sql.NullBool
	ReceptionID int64
	CreatedAt   time.Time
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
}
