// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/khozaei/healthio/ent/patient"
)

// Patient is the model entity for the Patient schema.
type Patient struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// FirstName holds the value of the "first_name" field.
	FirstName string `json:"first_name,omitempty"`
	// LastName holds the value of the "last_name" field.
	LastName string `json:"last_name,omitempty"`
	// FatherName holds the value of the "father_name" field.
	FatherName string `json:"father_name,omitempty"`
	// Phone holds the value of the "phone" field.
	Phone string `json:"phone,omitempty"`
	// NationalCode holds the value of the "national_code" field.
	NationalCode string `json:"national_code,omitempty"`
	// IdentityCode holds the value of the "identity_code" field.
	IdentityCode string `json:"identity_code,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt time.Time `json:"deleted_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PatientQuery when eager-loading is set.
	Edges        PatientEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PatientEdges holds the relations/edges for other nodes in the graph.
type PatientEdges struct {
	// Attachment holds the value of the attachment edge.
	Attachment []*Attachment `json:"attachment,omitempty"`
	// Reception holds the value of the reception edge.
	Reception []*Reception `json:"reception,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// AttachmentOrErr returns the Attachment value or an error if the edge
// was not loaded in eager-loading.
func (e PatientEdges) AttachmentOrErr() ([]*Attachment, error) {
	if e.loadedTypes[0] {
		return e.Attachment, nil
	}
	return nil, &NotLoadedError{edge: "attachment"}
}

// ReceptionOrErr returns the Reception value or an error if the edge
// was not loaded in eager-loading.
func (e PatientEdges) ReceptionOrErr() ([]*Reception, error) {
	if e.loadedTypes[1] {
		return e.Reception, nil
	}
	return nil, &NotLoadedError{edge: "reception"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Patient) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case patient.FieldID:
			values[i] = new(sql.NullInt64)
		case patient.FieldFirstName, patient.FieldLastName, patient.FieldFatherName, patient.FieldPhone, patient.FieldNationalCode, patient.FieldIdentityCode:
			values[i] = new(sql.NullString)
		case patient.FieldCreatedAt, patient.FieldUpdatedAt, patient.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Patient fields.
func (pa *Patient) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case patient.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			pa.ID = int(value.Int64)
		case patient.FieldFirstName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field first_name", values[i])
			} else if value.Valid {
				pa.FirstName = value.String
			}
		case patient.FieldLastName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_name", values[i])
			} else if value.Valid {
				pa.LastName = value.String
			}
		case patient.FieldFatherName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field father_name", values[i])
			} else if value.Valid {
				pa.FatherName = value.String
			}
		case patient.FieldPhone:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field phone", values[i])
			} else if value.Valid {
				pa.Phone = value.String
			}
		case patient.FieldNationalCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field national_code", values[i])
			} else if value.Valid {
				pa.NationalCode = value.String
			}
		case patient.FieldIdentityCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field identity_code", values[i])
			} else if value.Valid {
				pa.IdentityCode = value.String
			}
		case patient.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				pa.CreatedAt = value.Time
			}
		case patient.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				pa.UpdatedAt = value.Time
			}
		case patient.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				pa.DeletedAt = value.Time
			}
		default:
			pa.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Patient.
// This includes values selected through modifiers, order, etc.
func (pa *Patient) Value(name string) (ent.Value, error) {
	return pa.selectValues.Get(name)
}

// QueryAttachment queries the "attachment" edge of the Patient entity.
func (pa *Patient) QueryAttachment() *AttachmentQuery {
	return NewPatientClient(pa.config).QueryAttachment(pa)
}

// QueryReception queries the "reception" edge of the Patient entity.
func (pa *Patient) QueryReception() *ReceptionQuery {
	return NewPatientClient(pa.config).QueryReception(pa)
}

// Update returns a builder for updating this Patient.
// Note that you need to call Patient.Unwrap() before calling this method if this Patient
// was returned from a transaction, and the transaction was committed or rolled back.
func (pa *Patient) Update() *PatientUpdateOne {
	return NewPatientClient(pa.config).UpdateOne(pa)
}

// Unwrap unwraps the Patient entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (pa *Patient) Unwrap() *Patient {
	_tx, ok := pa.config.driver.(*txDriver)
	if !ok {
		panic("ent: Patient is not a transactional entity")
	}
	pa.config.driver = _tx.drv
	return pa
}

// String implements the fmt.Stringer.
func (pa *Patient) String() string {
	var builder strings.Builder
	builder.WriteString("Patient(")
	builder.WriteString(fmt.Sprintf("id=%v, ", pa.ID))
	builder.WriteString("first_name=")
	builder.WriteString(pa.FirstName)
	builder.WriteString(", ")
	builder.WriteString("last_name=")
	builder.WriteString(pa.LastName)
	builder.WriteString(", ")
	builder.WriteString("father_name=")
	builder.WriteString(pa.FatherName)
	builder.WriteString(", ")
	builder.WriteString("phone=")
	builder.WriteString(pa.Phone)
	builder.WriteString(", ")
	builder.WriteString("national_code=")
	builder.WriteString(pa.NationalCode)
	builder.WriteString(", ")
	builder.WriteString("identity_code=")
	builder.WriteString(pa.IdentityCode)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(pa.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(pa.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("deleted_at=")
	builder.WriteString(pa.DeletedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Patients is a parsable slice of Patient.
type Patients []*Patient
