// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/khozaei/healthio/ent/patient"
	"github.com/khozaei/healthio/ent/predicate"
	"github.com/khozaei/healthio/ent/reception"
	"github.com/khozaei/healthio/ent/visit"
)

// ReceptionQuery is the builder for querying Reception entities.
type ReceptionQuery struct {
	config
	ctx         *QueryContext
	order       []reception.OrderOption
	inters      []Interceptor
	predicates  []predicate.Reception
	withPatient *PatientQuery
	withVisit   *VisitQuery
	withFKs     bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ReceptionQuery builder.
func (rq *ReceptionQuery) Where(ps ...predicate.Reception) *ReceptionQuery {
	rq.predicates = append(rq.predicates, ps...)
	return rq
}

// Limit the number of records to be returned by this query.
func (rq *ReceptionQuery) Limit(limit int) *ReceptionQuery {
	rq.ctx.Limit = &limit
	return rq
}

// Offset to start from.
func (rq *ReceptionQuery) Offset(offset int) *ReceptionQuery {
	rq.ctx.Offset = &offset
	return rq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (rq *ReceptionQuery) Unique(unique bool) *ReceptionQuery {
	rq.ctx.Unique = &unique
	return rq
}

// Order specifies how the records should be ordered.
func (rq *ReceptionQuery) Order(o ...reception.OrderOption) *ReceptionQuery {
	rq.order = append(rq.order, o...)
	return rq
}

// QueryPatient chains the current query on the "patient" edge.
func (rq *ReceptionQuery) QueryPatient() *PatientQuery {
	query := (&PatientClient{config: rq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := rq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := rq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(reception.Table, reception.FieldID, selector),
			sqlgraph.To(patient.Table, patient.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, reception.PatientTable, reception.PatientColumn),
		)
		fromU = sqlgraph.SetNeighbors(rq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryVisit chains the current query on the "visit" edge.
func (rq *ReceptionQuery) QueryVisit() *VisitQuery {
	query := (&VisitClient{config: rq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := rq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := rq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(reception.Table, reception.FieldID, selector),
			sqlgraph.To(visit.Table, visit.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, reception.VisitTable, reception.VisitColumn),
		)
		fromU = sqlgraph.SetNeighbors(rq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Reception entity from the query.
// Returns a *NotFoundError when no Reception was found.
func (rq *ReceptionQuery) First(ctx context.Context) (*Reception, error) {
	nodes, err := rq.Limit(1).All(setContextOp(ctx, rq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{reception.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (rq *ReceptionQuery) FirstX(ctx context.Context) *Reception {
	node, err := rq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Reception ID from the query.
// Returns a *NotFoundError when no Reception ID was found.
func (rq *ReceptionQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = rq.Limit(1).IDs(setContextOp(ctx, rq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{reception.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (rq *ReceptionQuery) FirstIDX(ctx context.Context) int {
	id, err := rq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Reception entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Reception entity is found.
// Returns a *NotFoundError when no Reception entities are found.
func (rq *ReceptionQuery) Only(ctx context.Context) (*Reception, error) {
	nodes, err := rq.Limit(2).All(setContextOp(ctx, rq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{reception.Label}
	default:
		return nil, &NotSingularError{reception.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (rq *ReceptionQuery) OnlyX(ctx context.Context) *Reception {
	node, err := rq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Reception ID in the query.
// Returns a *NotSingularError when more than one Reception ID is found.
// Returns a *NotFoundError when no entities are found.
func (rq *ReceptionQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = rq.Limit(2).IDs(setContextOp(ctx, rq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{reception.Label}
	default:
		err = &NotSingularError{reception.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (rq *ReceptionQuery) OnlyIDX(ctx context.Context) int {
	id, err := rq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Receptions.
func (rq *ReceptionQuery) All(ctx context.Context) ([]*Reception, error) {
	ctx = setContextOp(ctx, rq.ctx, "All")
	if err := rq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Reception, *ReceptionQuery]()
	return withInterceptors[[]*Reception](ctx, rq, qr, rq.inters)
}

// AllX is like All, but panics if an error occurs.
func (rq *ReceptionQuery) AllX(ctx context.Context) []*Reception {
	nodes, err := rq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Reception IDs.
func (rq *ReceptionQuery) IDs(ctx context.Context) (ids []int, err error) {
	if rq.ctx.Unique == nil && rq.path != nil {
		rq.Unique(true)
	}
	ctx = setContextOp(ctx, rq.ctx, "IDs")
	if err = rq.Select(reception.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (rq *ReceptionQuery) IDsX(ctx context.Context) []int {
	ids, err := rq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (rq *ReceptionQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, rq.ctx, "Count")
	if err := rq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, rq, querierCount[*ReceptionQuery](), rq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (rq *ReceptionQuery) CountX(ctx context.Context) int {
	count, err := rq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (rq *ReceptionQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, rq.ctx, "Exist")
	switch _, err := rq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (rq *ReceptionQuery) ExistX(ctx context.Context) bool {
	exist, err := rq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ReceptionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (rq *ReceptionQuery) Clone() *ReceptionQuery {
	if rq == nil {
		return nil
	}
	return &ReceptionQuery{
		config:      rq.config,
		ctx:         rq.ctx.Clone(),
		order:       append([]reception.OrderOption{}, rq.order...),
		inters:      append([]Interceptor{}, rq.inters...),
		predicates:  append([]predicate.Reception{}, rq.predicates...),
		withPatient: rq.withPatient.Clone(),
		withVisit:   rq.withVisit.Clone(),
		// clone intermediate query.
		sql:  rq.sql.Clone(),
		path: rq.path,
	}
}

// WithPatient tells the query-builder to eager-load the nodes that are connected to
// the "patient" edge. The optional arguments are used to configure the query builder of the edge.
func (rq *ReceptionQuery) WithPatient(opts ...func(*PatientQuery)) *ReceptionQuery {
	query := (&PatientClient{config: rq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	rq.withPatient = query
	return rq
}

// WithVisit tells the query-builder to eager-load the nodes that are connected to
// the "visit" edge. The optional arguments are used to configure the query builder of the edge.
func (rq *ReceptionQuery) WithVisit(opts ...func(*VisitQuery)) *ReceptionQuery {
	query := (&VisitClient{config: rq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	rq.withVisit = query
	return rq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		ReceptionFor time.Time `json:"reception_for,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Reception.Query().
//		GroupBy(reception.FieldReceptionFor).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (rq *ReceptionQuery) GroupBy(field string, fields ...string) *ReceptionGroupBy {
	rq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ReceptionGroupBy{build: rq}
	grbuild.flds = &rq.ctx.Fields
	grbuild.label = reception.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		ReceptionFor time.Time `json:"reception_for,omitempty"`
//	}
//
//	client.Reception.Query().
//		Select(reception.FieldReceptionFor).
//		Scan(ctx, &v)
func (rq *ReceptionQuery) Select(fields ...string) *ReceptionSelect {
	rq.ctx.Fields = append(rq.ctx.Fields, fields...)
	sbuild := &ReceptionSelect{ReceptionQuery: rq}
	sbuild.label = reception.Label
	sbuild.flds, sbuild.scan = &rq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ReceptionSelect configured with the given aggregations.
func (rq *ReceptionQuery) Aggregate(fns ...AggregateFunc) *ReceptionSelect {
	return rq.Select().Aggregate(fns...)
}

func (rq *ReceptionQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range rq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, rq); err != nil {
				return err
			}
		}
	}
	for _, f := range rq.ctx.Fields {
		if !reception.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if rq.path != nil {
		prev, err := rq.path(ctx)
		if err != nil {
			return err
		}
		rq.sql = prev
	}
	return nil
}

func (rq *ReceptionQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Reception, error) {
	var (
		nodes       = []*Reception{}
		withFKs     = rq.withFKs
		_spec       = rq.querySpec()
		loadedTypes = [2]bool{
			rq.withPatient != nil,
			rq.withVisit != nil,
		}
	)
	if rq.withPatient != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, reception.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Reception).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Reception{config: rq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, rq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := rq.withPatient; query != nil {
		if err := rq.loadPatient(ctx, query, nodes, nil,
			func(n *Reception, e *Patient) { n.Edges.Patient = e }); err != nil {
			return nil, err
		}
	}
	if query := rq.withVisit; query != nil {
		if err := rq.loadVisit(ctx, query, nodes,
			func(n *Reception) { n.Edges.Visit = []*Visit{} },
			func(n *Reception, e *Visit) { n.Edges.Visit = append(n.Edges.Visit, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (rq *ReceptionQuery) loadPatient(ctx context.Context, query *PatientQuery, nodes []*Reception, init func(*Reception), assign func(*Reception, *Patient)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*Reception)
	for i := range nodes {
		if nodes[i].patient_reception == nil {
			continue
		}
		fk := *nodes[i].patient_reception
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(patient.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "patient_reception" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (rq *ReceptionQuery) loadVisit(ctx context.Context, query *VisitQuery, nodes []*Reception, init func(*Reception), assign func(*Reception, *Visit)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Reception)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Visit(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(reception.VisitColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.reception_visit
		if fk == nil {
			return fmt.Errorf(`foreign-key "reception_visit" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "reception_visit" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (rq *ReceptionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := rq.querySpec()
	_spec.Node.Columns = rq.ctx.Fields
	if len(rq.ctx.Fields) > 0 {
		_spec.Unique = rq.ctx.Unique != nil && *rq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, rq.driver, _spec)
}

func (rq *ReceptionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(reception.Table, reception.Columns, sqlgraph.NewFieldSpec(reception.FieldID, field.TypeInt))
	_spec.From = rq.sql
	if unique := rq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if rq.path != nil {
		_spec.Unique = true
	}
	if fields := rq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, reception.FieldID)
		for i := range fields {
			if fields[i] != reception.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := rq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := rq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := rq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := rq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (rq *ReceptionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(rq.driver.Dialect())
	t1 := builder.Table(reception.Table)
	columns := rq.ctx.Fields
	if len(columns) == 0 {
		columns = reception.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if rq.sql != nil {
		selector = rq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if rq.ctx.Unique != nil && *rq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range rq.predicates {
		p(selector)
	}
	for _, p := range rq.order {
		p(selector)
	}
	if offset := rq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := rq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ReceptionGroupBy is the group-by builder for Reception entities.
type ReceptionGroupBy struct {
	selector
	build *ReceptionQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (rgb *ReceptionGroupBy) Aggregate(fns ...AggregateFunc) *ReceptionGroupBy {
	rgb.fns = append(rgb.fns, fns...)
	return rgb
}

// Scan applies the selector query and scans the result into the given value.
func (rgb *ReceptionGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rgb.build.ctx, "GroupBy")
	if err := rgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ReceptionQuery, *ReceptionGroupBy](ctx, rgb.build, rgb, rgb.build.inters, v)
}

func (rgb *ReceptionGroupBy) sqlScan(ctx context.Context, root *ReceptionQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(rgb.fns))
	for _, fn := range rgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*rgb.flds)+len(rgb.fns))
		for _, f := range *rgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*rgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ReceptionSelect is the builder for selecting fields of Reception entities.
type ReceptionSelect struct {
	*ReceptionQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (rs *ReceptionSelect) Aggregate(fns ...AggregateFunc) *ReceptionSelect {
	rs.fns = append(rs.fns, fns...)
	return rs
}

// Scan applies the selector query and scans the result into the given value.
func (rs *ReceptionSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rs.ctx, "Select")
	if err := rs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ReceptionQuery, *ReceptionSelect](ctx, rs.ReceptionQuery, rs, rs.inters, v)
}

func (rs *ReceptionSelect) sqlScan(ctx context.Context, root *ReceptionQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(rs.fns))
	for _, fn := range rs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*rs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
