// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/khozaei/healthio/ent/attachment"
	"github.com/khozaei/healthio/ent/patient"
	"github.com/khozaei/healthio/ent/reception"
	"github.com/khozaei/healthio/ent/schema"
	"github.com/khozaei/healthio/ent/visit"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	attachmentFields := schema.Attachment{}.Fields()
	_ = attachmentFields
	// attachmentDescCreatedAt is the schema descriptor for created_at field.
	attachmentDescCreatedAt := attachmentFields[2].Descriptor()
	// attachment.DefaultCreatedAt holds the default value on creation for the created_at field.
	attachment.DefaultCreatedAt = attachmentDescCreatedAt.Default.(time.Time)
	patientFields := schema.Patient{}.Fields()
	_ = patientFields
	// patientDescCreatedAt is the schema descriptor for created_at field.
	patientDescCreatedAt := patientFields[6].Descriptor()
	// patient.DefaultCreatedAt holds the default value on creation for the created_at field.
	patient.DefaultCreatedAt = patientDescCreatedAt.Default.(time.Time)
	receptionFields := schema.Reception{}.Fields()
	_ = receptionFields
	// receptionDescVisitDuration is the schema descriptor for visit_duration field.
	receptionDescVisitDuration := receptionFields[1].Descriptor()
	// reception.VisitDurationValidator is a validator for the "visit_duration" field. It is called by the builders before save.
	reception.VisitDurationValidator = receptionDescVisitDuration.Validators[0].(func(int) error)
	// receptionDescCreatedAt is the schema descriptor for created_at field.
	receptionDescCreatedAt := receptionFields[4].Descriptor()
	// reception.DefaultCreatedAt holds the default value on creation for the created_at field.
	reception.DefaultCreatedAt = receptionDescCreatedAt.Default.(time.Time)
	visitFields := schema.Visit{}.Fields()
	_ = visitFields
	// visitDescCreatedAt is the schema descriptor for created_at field.
	visitDescCreatedAt := visitFields[4].Descriptor()
	// visit.DefaultCreatedAt holds the default value on creation for the created_at field.
	visit.DefaultCreatedAt = visitDescCreatedAt.Default.(time.Time)
}
