// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Attachment is the predicate function for attachment builders.
type Attachment func(*sql.Selector)

// Patient is the predicate function for patient builders.
type Patient func(*sql.Selector)

// Reception is the predicate function for reception builders.
type Reception func(*sql.Selector)

// Visit is the predicate function for visit builders.
type Visit func(*sql.Selector)
